export {default as NavBar} from "./NavBar"; 
export {default as Routines} from "./Routines";
export {default as Activities} from "./Activities";
export {default as Home} from "./Home";
export {default as MyRoutines} from "./MyRoutines";
export {default as LogIn} from "./LogIn";
export {default as AddEditRoutines} from "./AddEditRoutines";
export {default as Routine} from "./Routine.js";
export {default as AddActivity} from "./AddActivity";
